spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: fmetin
  profiles:
    active:
      - dev
hoaxify:
  upload-path: picture-storage

---

spring:
  config:
    activate:
      on-profile: prod

hoaxify:
  upload-path: storage-prod

---

spring:
  config:
    activate:
      on-profile: dev

hoaxify:
  upload-path: storage-dev
